// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test3.json

#ifndef PAL_PUBLIC_RENDERER_SAMPLE_PROXY_H_
#define PAL_PUBLIC_RENDERER_SAMPLE_PROXY_H_

#include "content/public/renderer/render_frame.h"
#include "pal/ipc/pal_export.h"

namespace pal {

class PAL_EXPORT SampleProxy {
 public:
  SampleProxy(content::RenderFrame* frame);
  virtual ~SampleProxy() = default;

  void CallFunc(std::string arg1, std::string arg2);

  void ProcessData(int pal_async_callback_id,
                   std::string data,
                   int32_t callback_index);

  void SubscribeToEvent();

  bool Unsubscribe();
  bool Subscribe();

 private:
  content::RenderFrame* render_frame_;
};

}  // namespace pal

#endif  // PAL_PUBLIC_RENDERER_SAMPLE_PROXY_H_
