// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test4.json

#ifndef PAL_PUBLIC_BROWSER_NATIVE_DIALOGS_HOST_H_
#define PAL_PUBLIC_BROWSER_NATIVE_DIALOGS_HOST_H_

#include "content/public/browser/browser_message_filter.h"
#include "pal/ipc/pal_export.h"
#include "pal/public/interfaces/native_dialogs_interface.h"

namespace pal {

class PAL_EXPORT NativeDialogsHost : public content::BrowserMessageFilter {
 public:
  NativeDialogsHost();

  bool OnMessageReceived(const IPC::Message& message) override;

 private:
  ~NativeDialogsHost() override;

  DISALLOW_COPY_AND_ASSIGN(NativeDialogsHost);
};

}  // namespace pal

#endif  // PAL_PUBLIC_BROWSER_NATIVE_DIALOGS_HOST_H_