#!/bin/sh

PmLogCtl def chrome.runscript warning
PmLogCtl logkv chrome.runscript info launchTime place=start_chrome
######################################################################
                 #      Environment Variables       #
######################################################################

export TMPDIR="/tmp"

if test -d ${XDG_RUNTIME_DIR}; then
  export XDG_RUNTIME_DIR="${TMPDIR}/xdg"
fi

DEPLOY_DIR=$(dirname $(readlink -f $0))
BIN_DIR="/usr/bin/wam-demo"

USER_CACHE_CONF=${DEPLOY_DIR}/user_cachedir_conf
if [ -f ${USER_CACHE_CONF} ]; then
    CACHE_DIR=`cat ${USER_CACHE_CONF}`
else
    CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}"
fi

FONT_CONFIG_CONF=${DEPLOY_DIR}/font_config_conf.sh
if [ -x ${FONT_CONFIG_CONF} ]; then
    . ${FONT_CONFIG_CONF}
fi

CHROME_CACHE="${CACHE_DIR}/wam_demo"

######################################################################
                #      Target Environment          #
######################################################################
PmLogCtl logkv chrome.runscript info launchTime place=start_env

# temp code for security issue
chmod -R 777 ${CHROME_CACHE}
rm -f ${CHROME_CACHE}/Singleton*
rm -rf ${TMPDIR}/.org.chromium.*

######################################################################
                 #      Runtime Configuration       #
######################################################################
CHROME_COMPOSITING_FLAGS=" \
  --enable-accelerated-compositing\
  --enable-smooth-scrolling\
"
CHROME_FLAGS=" \
  --always-authorize-plugins\
  --disable-component-update\
  --disable-extensions\
  --disable-gpu-watchdog\
  --disable-infobars\
  --disable-new-video-renderer\
  --disable-translate\
  --disable-web-security\
  --enable-file-cookies\
  --enable-neva-ime\
  --gpu-no-context-lost\
  --ignore-gpu-blacklist\
  --in-process-gpu\
  --noerrdialogs\
  --no-sandbox\
  --start-maximized\
  --user-data-dir=${CHROME_CACHE}\
"

CHROME_FLAGS="${CHROME_COMPOSITING_FLAGS} ${CHROME_FLAGS}"

EXTRA_CONF=${CACHE_DIR}/extra_conf
if [ -f ${EXTRA_CONF} ]; then
    source ${EXTRA_CONF}
    echo "CHROME_FLAGS=${CHROME_FLAGS}"
fi

PmLogCtl logkv chrome.runscript info launchTime place=call_chrome

######################################################################
                #      Launch WamDemo           #
# REPLACE * is used to fill the compiled source version automatically #
# So, should not be removed.
######################################################################

echo ""
echo "----------------------------------------------------------------------"
echo "                       Launching Wam Demo                          "
### REPLACE URL ###
### REPLACE REVISION ###
### REPLACE BUILD TIME ###
echo "----------------------------------------------------------------------"
echo ""

exec ${DEPLOY_DIR}/wam_demo ${CHROME_FLAGS} "$@"
