#!/bin/sh

PmLogCtl def chrome.runscript warning
PmLogCtl logkv chrome.runscript info launchTime place=start_chrome
######################################################################
                 #      Environment Variables       #
######################################################################

export TMPDIR="/tmp"
export BROWSER_APP_ID=""
export APP_FOLDER_PATH=""
export EXTRA_PARAMS_JSON=""
# Setup 4Mb limitation mse audio buffer size
export MSE_AUDIO_BUFFER_SIZE_LIMIT=4194304
# Setup 50Mb limitation mse video buffer size
export MSE_VIDEO_BUFFER_SIZE_LIMIT=52428800
# Setup override_user_agent_string
export OVERRIDE_USER_AGENT_STRING="Mozilla/5.0 (Linux; NetCast; U) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/68.0.3440.0 Safari/537.36 SmartTV/6.0"
while [[ "$1" != ""  &&  "$2" != "" ]]; do
    PARAM=$1
    VALUE=$2
    case $PARAM in
        --appid)
            BROWSER_APP_ID=$VALUE
            ;;
        --folder)
            APP_FOLDER_PATH=$VALUE
            ;;
        --params)
            EXTRA_PARAMS_JSON=$VALUE
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            exit 1
            ;;
    esac
    shift
    shift
done

if [ -z ${APP_FOLDER_PATH} ]; then
    echo "ERROR: --folder info not provided \"$@\""
    exit 1
fi

if [ -z ${BROWSER_APP_ID} ]; then
    echo "ERROR: --appid info not provided \"$@\""
    exit 1
fi

if test -d ${XDG_RUNTIME_DIR}; then
  export XDG_RUNTIME_DIR="${TMPDIR}/xdg"
fi

DEPLOY_DIR=$(dirname $(readlink -f $0))

USER_CACHE_CONF=${DEPLOY_DIR}/user_cachedir_conf
if [ -f ${USER_CACHE_CONF} ]; then
    CACHE_DIR=`cat ${USER_CACHE_CONF}`
else
    CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}"
fi

FONT_CONFIG_CONF=${DEPLOY_DIR}/font_config_conf.sh
if [ -x ${FONT_CONFIG_CONF} ]; then
    . ${FONT_CONFIG_CONF}
fi

CHROME_CACHE="${CACHE_DIR}/app_shell"

# Add 'override_user_agent_string' key-value to EXTRA_PARAMS_JSON
EXTRA_PARAMS_JSON=$(echo $EXTRA_PARAMS_JSON|sed "s#^{\(.*\)}#{\1,\"override_user_agent_string\":\"${OVERRIDE_USER_AGENT_STRING}\"}#g")

######################################################################
                #      Target Environment          #
######################################################################
PmLogCtl logkv chrome.runscript info launchTime place=start_env

# temp code for security issue
chmod -R 777 ${CHROME_CACHE}
rm -f ${CHROME_CACHE}/Singleton*
rm -rf ${TMPDIR}/.org.chromium.*

######################################################################
                 #      Runtime Configuration       #
######################################################################
CHROME_COMPOSITING_FLAGS=" \
  --enable-accelerated-compositing\
  --enable-smooth-scrolling\
"
CHROME_FLAGS=" \
  --always-authorize-plugins\
  --autoplay-policy=no-user-gesture-required\
  --process-per-guest-webview\
  --disable-component-update\
  --disable-gpu-watchdog\
  --disable-infobars\
  --disable-new-video-renderer\
  --disable-translate\
  --disable-web-security\
  --enable-file-cookies\
  --enable-neva-ime\
  --gpu-no-context-lost\
  --ignore-gpu-blacklist\
  --in-process-gpu\
  --max-timeupdate-event-frequency=150\
  --mse-audio-buffer-size-limit=${MSE_AUDIO_BUFFER_SIZE_LIMIT}\
  --mse-video-buffer-size-limit=${MSE_VIDEO_BUFFER_SIZE_LIMIT}\
  --noerrdialogs\
  --no-sandbox\
  --no-zygote\
  --start-maximized\
  --user-data-dir=${CHROME_CACHE}\
  --webos-appid=${BROWSER_APP_ID}\
  --load-apps=${APP_FOLDER_PATH}\
  --v8-snapshot-blob-path=${APP_FOLDER_PATH}/snapshot_blob.bin\
"

CHROME_FLAGS="${CHROME_COMPOSITING_FLAGS} ${CHROME_FLAGS}"

JS_FLAGS=" \
  --configure_heap_details\
  --heap_growing_percent=1\
  --minimum_allocation_limit_growing_step_size=2\
  --high_fragmentation_slack=0\
  --external_allocation_hard_limit=64\
  --external_allocation_soft_limit=16\
"

EXTRA_CONF=${CACHE_DIR}/extra_conf
if [ -f ${EXTRA_CONF} ]; then
    source ${EXTRA_CONF}
    echo "CHROME_FLAGS=${CHROME_FLAGS}"
fi

PmLogCtl logkv chrome.runscript info launchTime place=call_chrome

######################################################################
                #      Launch AppShell           #
# REPLACE * is used to fill the compiled source version automatically #
# So, should not be removed.
######################################################################

echo ""
echo "----------------------------------------------------------------------"
echo "                       Launching App Shell                          "
### REPLACE URL ###
### REPLACE REVISION ###
### REPLACE BUILD TIME ###
echo "----------------------------------------------------------------------"
echo ""

exec ${DEPLOY_DIR}/app_shell ${CHROME_FLAGS} --launch-args="${EXTRA_PARAMS_JSON}" --js-flags="${JS_FLAGS}" "$@"
