// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test2.json

#include "remote_pal_ipc/remote_pal_ipc.h"

#include <mutex>

#include "remote_pal_ipc/intent_agent/intent_agent_remote_pal_interface_ipc.h"

namespace pal {

std::unique_ptr<IntentAgentInterface> intent_agent_interface_instance;
std::once_flag intent_agent_interface_instance_flag;

IntentAgentInterface* RemotePalIPC::GetIntentAgentInterface() {
  std::call_once(intent_agent_interface_instance_flag, []() {
    intent_agent_interface_instance.reset(
        new IntentAgentRemotePalInterfaceIPC());
  });
  return intent_agent_interface_instance.get();
}

}  // namespace pal
