// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test4.json

#include "pal/ipc/browser/native_dialogs/native_dialogs_host.h"

#define PalAddFiltersGen(AddFilterMethod) \
  AddFilterMethod(new pal::NativeDialogsHost);
#define PalMsgStartGen NativeDialogsMsgStart