// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test2.json

#include "pal/ipc/renderer/intent_agent/intent_agent_proxy.h"
#include "pal/ipc/intent_agent_messages.h"

namespace pal {

IntentAgentProxy::IntentAgentProxy(content::RenderFrame* frame)
    : render_frame_(frame) {}

void IntentAgentProxy::InvokeIntent(int pal_async_callback_id,
                                    const std::string& action,
                                    const std::string& type,
                                    const std::string& data,
                                    const std::string& app_id,
                                    int32_t callback_index) {
  if (render_frame_) {
    render_frame_->Send(new IntentAgentHostMsg_InvokeIntent(
        render_frame_->GetRoutingID(), pal_async_callback_id, action, type,
        data, app_id, callback_index));
  }
}

void IntentAgentProxy::RespondIntent(bool result,
                                     uint32_t session_id,
                                     const std::string& data) {
  if (render_frame_) {
    render_frame_->Send(new IntentAgentHostMsg_RespondIntent(
        render_frame_->GetRoutingID(), result, session_id, data));
  }
}

}  // namespace pal
