// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test2.json

#include "remote_pal_ipc/intent_agent/intent_agent_remote_pal_interface_ipc.h"

namespace pal {

void IntentAgentRemotePalInterfaceIPC::NotifyInvokeIntent(
    int pal_async_callback_id,
    int error_code,
    const std::string& data) {
  InvokeIntentRespondCallbackMAP::iterator it =
      invoke_intent_respond_callbacks_.find(pal_async_callback_id);
  if (it == invoke_intent_respond_callbacks_.end())
    return;
  it->second.Run(error_code, data);
}

}  // namespace pal
