// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test2.json

#ifndef REMOTE_PAL_IPC_INTENT_AGENT_INTENT_AGENT_REMOTE_PAL_INTERFACE_IPC_H_
#define REMOTE_PAL_IPC_INTENT_AGENT_INTENT_AGENT_REMOTE_PAL_INTERFACE_IPC_H_

#include <map>

#include "pal/public/interfaces/intent_agent_interface.h"
#include "remote_pal_ipc/intent_agent/intent_agent_remote_pal_observer.h"

namespace pal {

class IntentAgentRemotePalInterfaceIPC : public IntentAgentInterface {
 public:
  IntentAgentRemotePalInterfaceIPC();
  ~IntentAgentRemotePalInterfaceIPC() override;

  void InvokeIntent(
      const std::string& action,
      const std::string& type,
      const std::string& data,
      const std::string& app_id,
      int32_t callback_index,
      const InvokeIntentRespondCallback& on_invoke_intent_done) override;
  void RespondIntent(bool result,
                     uint32_t session_id,
                     const std::string& data) override;

 private:
  content::RenderFrame* getFrame() const;

  friend content::IntentAgentRemotePalObserver;

  void NotifyInvokeIntent(int pal_async_callback_id,
                          int error_code,
                          const std::string& data);

  using FrameCallbacksMAP = std::map<int, std::unique_ptr<FrameCallbacks>>;
  FrameCallbacksMAP callbacks_;

  using InvokeIntentRespondCallbackMAP =
      std::map<int, InvokeIntentRespondCallback>;
  InvokeIntentRespondCallbackMAP invoke_intent_respond_callbacks_;
  static int invoke_intent_callback_id_;

  template <typename _ID, typename _Map>
  static _ID GetAsyncMsgId(_ID& async_msg_id_, _Map& map);
};

}  // namespace pal

#endif  // REMOTE_PAL_IPC_INTENT_AGENT_INTENT_AGENT_REMOTE_PAL_INTERFACE_IPC_H_
