// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test2.json

#ifndef REMOTE_PAL_IPC_INTENT_AGENT_INTENT_AGENT_REMOTE_PAL_OBSERVER_H_
#define REMOTE_PAL_IPC_INTENT_AGENT_INTENT_AGENT_REMOTE_PAL_OBSERVER_H_

#include <string>
#include "content/public/renderer/render_frame_observer.h"

namespace content {

class CONTENT_EXPORT IntentAgentRemotePalObserver : public RenderFrameObserver {
 public:
  explicit IntentAgentRemotePalObserver(RenderFrame* render_frame);
  ~IntentAgentRemotePalObserver() override = default;
  void OnDestruct() override;

  bool OnMessageReceived(const IPC::Message& message) override;

 private:
  void OnInvokeIntentDone(int pal_async_callback_id,
                          int error_code,
                          std::string data);
};

}  // namespace content

#endif  // REMOTE_PAL_IPC_INTENT_AGENT_INTENT_AGENT_REMOTE_PAL_OBSERVER_H_
