// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test1.json

#ifndef PAL_PUBLIC_RENDERER_SYSTEM_INFO_PROXY_H_
#define PAL_PUBLIC_RENDERER_SYSTEM_INFO_PROXY_H_

#include "content/public/renderer/render_frame.h"
#include "pal/ipc/pal_export.h"

namespace pal {

class PAL_EXPORT SystemInfoProxy {
 public:
  SystemInfoProxy(content::RenderFrame* frame);
  virtual ~SystemInfoProxy() = default;

  void GetSSLCertPath(std::string& pal_ret);

 private:
  content::RenderFrame* render_frame_;
};

}  // namespace pal

#endif  // PAL_PUBLIC_RENDERER_SYSTEM_INFO_PROXY_H_
