// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test5.json

#include "remote_pal_ipc/remote_pal_ipc.h"

#include <mutex>

#include "remote_pal_ipc/native_controls/native_controls_remote_pal_interface_ipc.h"

namespace pal {}  // namespace pal
