/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "cbd6ac4848a540ea6646d4f79700cf531e4eb9f9"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
