// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test1.json

#ifndef PAL_PUBLIC_BROWSER_SYSTEM_INFO_HOST_H_
#define PAL_PUBLIC_BROWSER_SYSTEM_INFO_HOST_H_

#include "content/public/browser/browser_message_filter.h"
#include "pal/ipc/pal_export.h"
#include "pal/public/interfaces/system_info_interface.h"

namespace pal {

class PAL_EXPORT SystemInfoHost : public content::BrowserMessageFilter {
 public:
  SystemInfoHost();

  bool OnMessageReceived(const IPC::Message& message) override;

 private:
  ~SystemInfoHost() override;

  void OnGetSSLCertPath(std::string* pal_ret);

  DISALLOW_COPY_AND_ASSIGN(SystemInfoHost);
};

}  // namespace pal

#endif  // PAL_PUBLIC_BROWSER_SYSTEM_INFO_HOST_H_