// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test2.json

#ifndef PAL_PUBLIC_BROWSER_INTENT_AGENT_HOST_H_
#define PAL_PUBLIC_BROWSER_INTENT_AGENT_HOST_H_

#include "content/public/browser/browser_message_filter.h"
#include "pal/ipc/pal_export.h"
#include "pal/public/interfaces/intent_agent_interface.h"

namespace pal {

class PAL_EXPORT IntentAgentHost : public content::BrowserMessageFilter {
 public:
  IntentAgentHost();

  bool OnMessageReceived(const IPC::Message& message) override;

 private:
  ~IntentAgentHost() override;

  void OnInvokeIntentDone(int routing_id,
                          int pal_async_callback_id,
                          int32_t callback_index,
                          int error_code,
                          const std::string& data);

  void OnInvokeIntent(int* routing_id,
                      int pal_async_callback_id,
                      const std::string& action,
                      const std::string& type,
                      const std::string& data,
                      const std::string& app_id,
                      int32_t callback_index);

  void OnRespondIntent(int* routing_id,
                       bool result,
                       uint32_t session_id,
                       const std::string& data);

  base::WeakPtrFactory<IntentAgentHost> weak_ptr_factory_;
  DISALLOW_COPY_AND_ASSIGN(IntentAgentHost);
};

}  // namespace pal

#endif  // PAL_PUBLIC_BROWSER_INTENT_AGENT_HOST_H_