// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test1.json

#include "system_info_remote_pal_observer.h"

#include "pal/ipc/system_info_messages.h"
#include "pal/public/pal.h"
#include "pal/public/pal_factory.h"
#include "remote_pal_ipc/system_info/system_info_remote_pal_interface_ipc.h"

namespace content {

SystemInfoRemotePalObserver::SystemInfoRemotePalObserver(
    RenderFrame* render_frame)
    : RenderFrameObserver(render_frame) {}

void SystemInfoRemotePalObserver::OnDestruct() {
  delete this;
}

bool SystemInfoRemotePalObserver::OnMessageReceived(
    const IPC::Message& message) {
  bool handled = true;
  IPC_BEGIN_MESSAGE_MAP(SystemInfoRemotePalObserver, message)
  IPC_MESSAGE_UNHANDLED(handled = false)
  IPC_END_MESSAGE_MAP()
  return handled;
}

}  // namespace content
