// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test1.json

#include "remote_pal_ipc/system_info/system_info_remote_pal_interface_ipc.h"

namespace pal {}  // namespace pal
