// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test1.json

#ifndef REMOTE_PAL_IPC_SYSTEM_INFO_SYSTEM_INFO_REMOTE_PAL_OBSERVER_H_
#define REMOTE_PAL_IPC_SYSTEM_INFO_SYSTEM_INFO_REMOTE_PAL_OBSERVER_H_

#include <string>
#include "content/public/renderer/render_frame_observer.h"

namespace content {

class CONTENT_EXPORT SystemInfoRemotePalObserver : public RenderFrameObserver {
 public:
  explicit SystemInfoRemotePalObserver(RenderFrame* render_frame);
  ~SystemInfoRemotePalObserver() override = default;
  void OnDestruct() override;

  bool OnMessageReceived(const IPC::Message& message) override;

 private:
};

}  // namespace content

#endif  // REMOTE_PAL_IPC_SYSTEM_INFO_SYSTEM_INFO_REMOTE_PAL_OBSERVER_H_
