// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test1.json

#ifndef REMOTE_PAL_IPC_SYSTEM_INFO_SYSTEM_INFO_REMOTE_PAL_INTERFACE_IPC_H_
#define REMOTE_PAL_IPC_SYSTEM_INFO_SYSTEM_INFO_REMOTE_PAL_INTERFACE_IPC_H_

#include <map>

#include "pal/public/interfaces/system_info_interface.h"
#include "remote_pal_ipc/system_info/system_info_remote_pal_observer.h"

namespace pal {

class SystemInfoRemotePalInterfaceIPC : public SystemInfoInterface {
 public:
  SystemInfoRemotePalInterfaceIPC();
  ~SystemInfoRemotePalInterfaceIPC() override;

  std::string GetSSLCertPath() override;

 private:
  content::RenderFrame* getFrame() const;

  friend content::SystemInfoRemotePalObserver;

  using FrameCallbacksMAP = std::map<int, std::unique_ptr<FrameCallbacks>>;
  FrameCallbacksMAP callbacks_;

  template <typename _ID, typename _Map>
  static _ID GetAsyncMsgId(_ID& async_msg_id_, _Map& map);
};

}  // namespace pal

#endif  // REMOTE_PAL_IPC_SYSTEM_INFO_SYSTEM_INFO_REMOTE_PAL_INTERFACE_IPC_H_
