// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test1.json

#include "pal/ipc/browser/system_info/system_info_host.h"

#define PalAddFiltersGen(AddFilterMethod) \
  AddFilterMethod(new pal::SystemInfoHost);
#define PalMsgStartGen SystemInfoMsgStart