// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test1.json

// Multiply-included file, hence no include guard.
#include "pal/ipc/system_info_messages.h"
