// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test2.json

// Multiply-included message file, no traditional include guard
#include <string>

#include "ipc/ipc_message_macros.h"
#include "pal/ipc/pal_export.h"

#undef IPC_MESSAGE_EXPORT
#define IPC_MESSAGE_EXPORT PAL_EXPORT
#define IPC_MESSAGE_START IntentAgentMsgStart

IPC_MESSAGE_ROUTED3(IntentAgentMsg_InvokeIntentDone,
                    int /* pal_async_callback_id */,
                    int /* error_code */,
                    std::string /* data */)
IPC_MESSAGE_ROUTED6(IntentAgentHostMsg_InvokeIntent,
                    int /* pal_async_callback_id */,
                    std::string /* action */,
                    std::string /* type */,
                    std::string /* data */,
                    std::string /* app_id */,
                    int32_t /* callback_index */)
IPC_MESSAGE_ROUTED3(IntentAgentHostMsg_RespondIntent,
                    bool /* result */,
                    uint32_t /* session_id */,
                    std::string /* data */)
