// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test2.json

#include "pal/ipc/browser/intent_agent/intent_agent_host.h"

#define PalAddFiltersGen(AddFilterMethod) \
  AddFilterMethod(new pal::IntentAgentHost);
#define PalMsgStartGen IntentAgentMsgStart