// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test2.json

// Multiply-included file, hence no include guard.
#include "pal/ipc/intent_agent_messages.h"
