// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test3.json

// Multiply-included file, hence no include guard.
#include "pal/ipc/sample_messages.h"
