// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test3.json

#include "pal/ipc/browser/sample/sample_host.h"

#define PalAddFiltersGen(AddFilterMethod) AddFilterMethod(new pal::SampleHost);
#define PalMsgStartGen SampleMsgStart