// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test3.json

#ifndef REMOTE_PAL_IPC_SAMPLE_SAMPLE_REMOTE_PAL_OBSERVER_H_
#define REMOTE_PAL_IPC_SAMPLE_SAMPLE_REMOTE_PAL_OBSERVER_H_

#include <string>
#include "content/public/renderer/render_frame_observer.h"

namespace content {

class CONTENT_EXPORT SampleRemotePalObserver : public RenderFrameObserver {
 public:
  explicit SampleRemotePalObserver(RenderFrame* render_frame);
  ~SampleRemotePalObserver() override = default;
  void OnDestruct() override;

  bool OnMessageReceived(const IPC::Message& message) override;

 private:
  void OnProcessDataDone(int pal_async_callback_id,
                         int error_code,
                         std::string data);
  void OnSampleUpdate(const std::string& value);
};

}  // namespace content

#endif  // REMOTE_PAL_IPC_SAMPLE_SAMPLE_REMOTE_PAL_OBSERVER_H_
