// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test5.json

// Multiply-included message file, no traditional include guard
#include <string>

#include "ipc/ipc_message_macros.h"
#include "pal/ipc/pal_export.h"

#undef IPC_MESSAGE_EXPORT
#define IPC_MESSAGE_EXPORT PAL_EXPORT
#define IPC_MESSAGE_START NativeControlsMsgStart

IPC_MESSAGE_ROUTED0(NativeControlsHostMsg_Unsubscribe)
IPC_MESSAGE_ROUTED0(NativeControlsHostMsg_Subscribe)
IPC_MESSAGE_ROUTED1(NativeControlsMsg_ColorChosen, int /* color */)
