// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test5.json

#include "pal/ipc/browser/native_controls/native_controls_host.h"

#define PalAddFiltersGen(AddFilterMethod) \
  AddFilterMethod(new pal::NativeControlsHost);
#define PalMsgStartGen NativeControlsMsgStart