// This file is generated by PAL generator, do not modify.
// To make changes, modify the source file:
// test5.json

// Multiply-included file, hence no include guard.
#include "pal/ipc/native_controls_messages.h"
